### ISSUE TITLE
Model Querying - Basics - 模型查询(基础) 实例错误

### ISSUE THREAD

**Issue by DanielZhui** [demopark/sequelize-docs-Zh-CN#61]
**sequelize 文档版本**
(V6)

**sequelize 目录章节**
(Model Querying - Basics - 模型查询(基础))

**反馈描述**
```
Model.findAll({
  attributes: [
    'foo',
    [sequelize.fn('COUNT', sequelize.col('hats')), 'n_hats']
    'bar'
  ]
});
```
这里直接使用聚合搜索而不分组不是会报错吗？

[模型查询](https://github.com/demopark/sequelize-docs-Zh-CN/blob/master/core-concepts/model-querying-basics.md)

**Comment by demopark** [comment]
标准SQL中，要查询非聚合列必须在GROUP BY子句中，否则会 alert `Column is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.`。而MySQL数据库中，进行了非ANSI标准的扩展，允许SELECT后含有非GROUP BY的列。这种写法按照官方文档中的说法是为了提高性能，避免不必要的排序和分组。
但是要注意，在这种设定下，一定要明确自己想要的结果到底是什么，以及实际执行的SQL语句返回结果，是否符合自己的预期。
MySQL在执行这类查询语句时，它会默认理解为，没写到GROUP BY子句的列，其列值是唯一的，如果GROUP BY省略的列值其实并不唯一，那么最好不要使用这项功能。
